
const BASE="https://yfawrenhudjomhnglfhq.supabase.co";
const API=BASE+"/functions/v1/allegro-creator-api";
const PUB="sb_publishable_3KY--8Y_uuKEdfdumC2txg__OWTRo2p";
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ALLEGRO Creator Portal</title><meta name="theme-color" content="#070a12"><style>
:root{--bg:#070a12;--panel:#101624;--line:#2a374e;--text:#f7f8fb;--muted:#a9b4c8;--gold:#f0be58;--cyan:#45ead4;--violet:#8d70ff}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:radial-gradient(circle at 85% 0,#2b1a50,transparent 32%),radial-gradient(circle at 10% 10%,#0c372f,transparent 28%),var(--bg);color:var(--text)}.wrap{width:min(1120px,92vw);margin:auto}header{position:sticky;top:0;background:#070a12e8;border-bottom:1px solid #ffffff16;backdrop-filter:blur(16px);z-index:10}.head{height:70px;display:flex;align-items:center;gap:15px}.brand{font-weight:1000;letter-spacing:.08em}.brand b{color:var(--gold)}.pill{margin-left:auto;font-size:.7rem;background:#173528;color:#baffde;border:1px solid #285d49;padding:7px 10px;border-radius:999px}main{padding:48px 0 80px}.hero{display:grid;grid-template-columns:1fr .85fr;gap:24px;align-items:start}.eyebrow{color:var(--cyan);letter-spacing:.16em;font-weight:900;font-size:.72rem}h1{font-size:clamp(46px,7vw,84px);line-height:.9;letter-spacing:-.055em;margin:12px 0 18px}.lead{color:#c6cedd;line-height:1.6}.card{background:#101624e8;border:1px solid var(--line);border-radius:22px;padding:20px}.auth{display:grid;gap:11px}input,select,textarea{width:100%;background:#090e18;color:white;border:1px solid #3a4760;border-radius:11px;padding:12px}textarea{min-height:90px}.btn{border:1px solid #3b4861;background:#151c2d;color:white;border-radius:999px;padding:11px 16px;font-weight:900;cursor:pointer}.btn.primary{border:0;background:linear-gradient(135deg,var(--gold),#ffdc8c);color:#111}.btn.cyan{border:0;background:linear-gradient(135deg,var(--cyan),#a4f9ec);color:#091411}.row{display:flex;gap:9px;flex-wrap:wrap}.muted{color:var(--muted);font-size:.86rem;line-height:1.5}.msg{min-height:24px;color:#9cf4d2;font-size:.9rem}.dash{display:none;margin-top:28px}.dash.on{display:block}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.full{grid-column:1/-1}.list{display:grid;gap:8px;margin-top:12px}.item{padding:12px;border:1px solid #ffffff12;border-radius:13px;background:#ffffff05;display:flex;justify-content:space-between;gap:10px;align-items:center}.item small{color:#95a2b8}.status{font-size:.65rem;font-weight:900;letter-spacing:.07em;padding:5px 8px;border-radius:999px;background:#1c2c25;color:#adf5d1}.progress{height:8px;background:#242e42;border-radius:999px;overflow:hidden;margin-top:8px}.progress i{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--gold),var(--cyan));transition:width .15s}.section-title{font-size:1.4rem;margin:0 0 8px}.hidden{display:none!important}@media(max-width:820px){.hero,.grid{grid-template-columns:1fr}.full{grid-column:auto}}</style></head>
<body><header><div class="wrap head"><div class="brand"><b>ALLEGRO</b> CREATOR PORTAL</div><div class="pill">OWNED-FIRST CREATOR STACK</div></div></header>
<main class="wrap"><section class="hero"><div><div class="eyebrow">FROM FILE TO FAN</div><h1>Own your<br>creator journey.</h1><p class="lead">Create your artist identity, prepare releases, upload masters, record rights ownership, submit for review and track your ALLEGRO catalogue from one place.</p><p class="muted">Audio masters are stored in a private bucket. Public listening is served through controlled stream authorization rather than exposing raw master files.</p><p class="muted"><strong>Musician-first rule:</strong> you keep ownership of your masters by default, direct fan transactions use a 90/10 creator-first split, small earned balances roll over, and editorial playlist placement cannot be bought. <a href="https://yfawrenhudjomhnglfhq.supabase.co/functions/v1/allegro-creator-charter" style="color:#45ead4;font-weight:900">Read the Creator Fairness Charter →</a></p></div>
<div class="card auth" id="authCard"><h2 class="section-title">Creator access</h2><input id="email" type="email" placeholder="Email"><input id="password" type="password" minlength="8" placeholder="Password (8+ characters)"><div class="row"><button class="btn primary" id="login">LOG IN</button><button class="btn" id="signup">CREATE ACCOUNT</button></div><div class="msg" id="authMsg"></div><div class="muted">New accounts may require email confirmation before the first login, depending on the current Auth setting.</div><hr style="border:0;border-top:1px solid #2a374e;width:100%;margin:8px 0"><h3 style="margin:0">Not ready to upload yet?</h3><div class="muted">Join the Founding Artists call and we can keep you informed while you prepare your release.</div><input id="interestName" placeholder="Artist / stage name"><input id="interestEmail" type="email" placeholder="Email"><input id="interestPhone" placeholder="Phone / WhatsApp (optional)"><input id="interestGenre" placeholder="Genre / sound"><label class="muted" style="display:flex;gap:8px;align-items:flex-start"><input id="interestConsent" type="checkbox" style="width:auto;margin-top:3px">I agree that ALLEGRO may contact me about the Founding Artists programme.</label><button class="btn cyan" id="interestBtn">I'M INTERESTED</button><div class="msg" id="interestMsg"></div></div></section>

<section class="dash" id="dash"><div class="row" style="justify-content:space-between;align-items:center"><div><div class="eyebrow">CREATOR DASHBOARD</div><h2 style="margin:8px 0">Build your catalogue</h2></div><button class="btn" id="logout">LOG OUT</button></div>
<div class="grid">
<div class="card"><h3 class="section-title">1. Artist profile</h3><div id="artistExisting" class="list"></div><form id="artistForm" class="auth"><input name="stage_name" placeholder="Artist / stage name" required><input name="city" placeholder="City"><input name="country_code" placeholder="Country code, e.g. ZA"><textarea name="bio" placeholder="Short artist bio"></textarea><button class="btn primary">CREATE ARTIST PROFILE</button></form></div>
<div class="card"><h3 class="section-title">2. Release</h3><form id="releaseForm" class="auth"><select name="artist_id" class="artistSelect" required></select><input name="title" placeholder="Release title" required><select name="release_type"><option>single</option><option>ep</option><option>album</option><option>live</option><option>compilation</option></select><input name="release_date" type="date"><input name="copyright_line" placeholder="Copyright line"><button class="btn primary">CREATE RELEASE</button></form><div id="releaseList" class="list"></div></div>
<div class="card"><h3 class="section-title">3. Track metadata</h3><form id="trackForm" class="auth"><select name="artist_id" class="artistSelect" required></select><select name="release_id" id="releaseSelect"><option value="">No release / attach later</option></select><input name="title" placeholder="Track title" required><input name="track_number" type="number" min="1" placeholder="Track number"><input name="genre_tags" placeholder="Genres, comma separated"><button class="btn primary">CREATE TRACK</button></form><div id="trackList" class="list"></div></div>
<div class="card"><h3 class="section-title">4. Master audio</h3><select id="audioTrack"></select><input id="audioFile" type="file" accept="audio/*"><button class="btn cyan" id="uploadAudio">UPLOAD MASTER</button><div class="progress"><i id="audioProgress"></i></div><div class="msg" id="uploadMsg"></div><div class="muted">Large audio uses resumable TUS upload in 6 MB chunks. The original master remains private.</div></div>
<div class="card"><h3 class="section-title">5. Rights declaration</h3><form id="rightsForm" class="auth"><select name="track_id" class="trackSelect"></select><select name="right_type"><option value="master">Master</option><option value="composition">Composition</option><option value="publishing">Publishing</option><option value="performer">Performer</option></select><input name="claimant_name" placeholder="Rights claimant" required><input name="share_percent" type="number" min="0" max="100" step=".01" placeholder="Share %" required><button class="btn primary">ADD RIGHTS CLAIM</button></form><div class="muted">A track needs master-right shares totalling 100% plus an uploaded audio master before it can be submitted for review.</div></div>
<div class="card"><h3 class="section-title">6. Submit for review</h3><select id="reviewTrack" class="trackSelect"></select><button class="btn primary" id="reviewBtn">SUBMIT TRACK</button><div class="msg" id="reviewMsg"></div><div class="muted">Submission does not automatically publish the track. ALLEGRO review must confirm rights and streaming readiness first.</div></div>
<div class="card full"><h3 class="section-title">Wallet & royalties</h3><div id="walletList" class="list"></div><div class="muted">Wallet figures only appear when actual accruals are posted by the controlled royalty ledger. No estimated earnings are presented as money owed.</div></div>
<div class="card full hidden" id="adminDesk"><div class="row" style="justify-content:space-between;align-items:center"><div><div class="eyebrow">OWNER MODERATION</div><h3 class="section-title" style="margin-top:7px">Review queue</h3></div><button class="btn" id="refreshAdmin">REFRESH</button></div><div class="muted">Approvals are server-gated: a private master and exactly 100% declared master rights are required before publication.</div><div id="adminQueue" class="list"></div><div class="msg" id="adminMsg"></div></div>
</div><div class="msg" id="mainMsg"></div></section></main>
<script>
const BASE="https://yfawrenhudjomhnglfhq.supabase.co",PUB="sb_publishable_3KY--8Y_uuKEdfdumC2txg__OWTRo2p",CREATOR=BASE+"/functions/v1/allegro-creator-api",LEAD=BASE+"/functions/v1/allegro-lead";
let token=localStorage.getItem("allegro_access_token")||"",state={artists:[],releases:[],tracks:[],wallets:[]};
const $=s=>document.querySelector(s), $=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]);
const msg=(el,t,bad=false)=>{el.textContent=t;el.style.color=bad?"#ff9f9f":"#9cf4d2"};
async function auth(path,body){const r=await fetch(BASE+"/auth/v1/"+path,{method:"POST",headers:{apikey:PUB,"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.msg||j.message||j.error_description||j.error||"Authentication failed");return j}
async function api(action,body,method="POST"){const r=await fetch(CREATOR+"?action="+encodeURIComponent(action),{method,headers:{authorization:"Bearer "+token,"content-type":"application/json"},body:method==="GET"?undefined:JSON.stringify(body||{})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||"Request failed");return j}
async function login(){try{const j=await auth("token?grant_type=password",{email:$("#email").value.trim(),password:$("#password").value});token=j.access_token||"";if(!token)throw new Error("No session returned");localStorage.setItem("allegro_access_token",token);msg($("#authMsg"),"Logged in.");await load()}catch(e){msg($("#authMsg"),e.message,true)}}
async function signup(){try{const j=await auth("signup",{email:$("#email").value.trim(),password:$("#password").value});if(j.access_token){token=j.access_token;localStorage.setItem("allegro_access_token",token);msg($("#authMsg"),"Account created and signed in.");await load()}else msg($("#authMsg"),"Account created. Check your email if confirmation is required, then log in.")}catch(e){msg($("#authMsg"),e.message,true)}}
$("#login").onclick=login;$("#signup").onclick=signup;$("#logout").onclick=()=>{localStorage.removeItem("allegro_access_token");token="";$("#dash").classList.remove("on");$("#authCard").classList.remove("hidden");msg($("#authMsg"),"Logged out.")};
$("#interestBtn").onclick=async()=>{const el=$("#interestMsg");try{if(!$("#interestConsent").checked)throw new Error("Please consent to contact first.");const p=new URLSearchParams(location.search);const payload={"form-name":"allegro-artist-interest","bot-field":"","artist_name":$("#interestName").value.trim(),"email":$("#interestEmail").value.trim(),"phone":$("#interestPhone").value.trim(),"genre":$("#interestGenre").value.trim(),"consent_contact":"yes","utm_source":p.get("utm_source")||"creator_portal","utm_medium":p.get("utm_medium")||"owned","utm_campaign":p.get("utm_campaign")||"founding_artists"};const r=await fetch(LEAD,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Could not save interest.");msg(el,"You're on the Founding Artists list.");$("#interestBtn").disabled=true}catch(e){msg(el,e.message,true)}};
function selectOptions(sel,rows,label){sel.innerHTML=rows.length?rows.map(x=>'<option value="'+x.id+'">'+(x[label]||"Untitled")+'</option>').join(""):'<option value="">Create the previous item first</option>'}
function render(){
 $$(".artistSelect").forEach(s=>selectOptions(s,state.artists,"stage_name"));selectOptions($("#releaseSelect"),state.releases,"title");$("#releaseSelect").insertAdjacentHTML("afterbegin",'<option value="">No release / attach later</option>');$$(".trackSelect").forEach(s=>selectOptions(s,state.tracks,"title"));selectOptions($("#audioTrack"),state.tracks,"title");
 $("#artistExisting").innerHTML=state.artists.map(a=>'<div class="item"><div><b>'+esc(a.stage_name)+'</b><br><small>'+esc(a.slug)+'</small></div><span class="status">'+esc(a.status)+'</span></div>').join("");
 $("#artistForm").classList.toggle("hidden",state.artists.length>0);
 $("#releaseList").innerHTML=state.releases.map(x=>'<div class="item"><div><b>'+esc(x.title)+'</b><br><small>'+esc(x.release_type)+'</small></div><span class="status">'+esc(x.status)+'</span></div>').join("");
 $("#trackList").innerHTML=state.tracks.map(x=>'<div class="item"><div><b>'+esc(x.title)+'</b><br><small>'+(x.audio_object_path?"MASTER UPLOADED":"NO AUDIO YET")+'</small></div><span class="status">'+esc(x.status)+'</span></div>').join("");
 $("#walletList").innerHTML=state.wallets.length?state.wallets.map(w=>'<div class="item"><div><b>'+esc(w.currency)+' wallet</b><br><small>Pending '+(Number(w.pending_cents||0)/100).toFixed(2)+' · Available '+(Number(w.available_cents||0)/100).toFixed(2)+' · Paid '+(Number(w.paid_cents||0)/100).toFixed(2)+'</small></div></div>').join(""):'<div class="muted">Wallet will be created with the artist profile.</div>';
 $("#adminDesk").classList.toggle("hidden",!state.user?.admin);if(state.user?.admin)loadAdminQueue();
}
async function loadAdminQueue(){if(!state.user?.admin)return;try{const j=await api("admin_review_queue",null,"GET");const items=j.queue||[];$("#adminQueue").innerHTML=items.length?items.map(q=>{const e=q.entity||{},a=e.artist||{},rights=q.rights||[],master=rights.filter(r=>r.right_type==="master").reduce((s,r)=>s+Number(r.share_bps||0),0);return '<div class="item" style="align-items:flex-start"><div style="flex:1"><b>'+esc(e.title||q.entity_type)+'</b><br><small>'+esc(a.stage_name||"Unknown artist")+' · master rights '+(master/100).toFixed(2)+'% · '+(e.audio_object_path?"MASTER PRESENT":"NO MASTER")+'</small><div class="row" style="margin-top:8px"><button class="btn cyan" onclick="adminDecision(\''+q.id+'\',\'approved\')">APPROVE</button><button class="btn" onclick="adminDecision(\''+q.id+'\',\'changes_requested\')">REQUEST CHANGES</button><button class="btn" onclick="adminDecision(\''+q.id+'\',\'rejected\')">REJECT</button></div></div><span class="status">'+esc(q.status)+'</span></div>'}).join(""):'<div class="muted">No pending submissions.</div>'}catch(e){msg($("#adminMsg"),e.message,true)}}
async function adminDecision(id,decision){const notes=window.prompt("Reviewer notes (optional)")||"";try{await api("admin_decide",{moderation_id:id,decision,notes});msg($("#adminMsg"),"Decision saved.");await loadAdminQueue();await load()}catch(e){msg($("#adminMsg"),e.message,true)}}
$("#refreshAdmin").onclick=loadAdminQueue;
async function load(){try{const j=await api("dashboard",null,"GET");state=j;$("#authCard").classList.add("hidden");$("#dash").classList.add("on");render()}catch(e){localStorage.removeItem("allegro_access_token");token="";$("#dash").classList.remove("on");$("#authCard").classList.remove("hidden");msg($("#authMsg"),e.message,true)}}
function formObj(form){return Object.fromEntries(new FormData(form).entries())}
$("#artistForm").onsubmit=async e=>{e.preventDefault();try{await api("create_artist",formObj(e.currentTarget));e.currentTarget.reset();await load();msg($("#mainMsg"),"Artist profile created.")}catch(x){msg($("#mainMsg"),x.message,true)}};
$("#releaseForm").onsubmit=async e=>{e.preventDefault();try{await api("create_release",formObj(e.currentTarget));e.currentTarget.reset();await load();msg($("#mainMsg"),"Release created.")}catch(x){msg($("#mainMsg"),x.message,true)}};
$("#trackForm").onsubmit=async e=>{e.preventDefault();try{const o=formObj(e.currentTarget);o.genre_tags=String(o.genre_tags||"").split(",").map(x=>x.trim()).filter(Boolean);await api("create_track",o);e.currentTarget.reset();await load();msg($("#mainMsg"),"Track created.")}catch(x){msg($("#mainMsg"),x.message,true)}};
$("#rightsForm").onsubmit=async e=>{e.preventDefault();try{const o=formObj(e.currentTarget);o.share_bps=Math.round(Number(o.share_percent)*100);delete o.share_percent;await api("add_right",o);e.currentTarget.reset();msg($("#mainMsg"),"Rights claim added.")}catch(x){msg($("#mainMsg"),x.message,true)}};
$("#reviewBtn").onclick=async()=>{try{const j=await api("request_review",{track_id:$("#reviewTrack").value});msg($("#reviewMsg"),"Submitted for ALLEGRO review.");await load()}catch(e){msg($("#reviewMsg"),e.message,true)}};
function meta(v){return btoa(unescape(encodeURIComponent(v)))}
async function tusUpload(file,target){
 const endpoint=target.upload.tus_url,offsetStep=6*1024*1024;const headers={authorization:"Bearer "+token,apikey:PUB,"Tus-Resumable":"1.0.0","Upload-Length":String(file.size),"Upload-Metadata":["bucketName "+meta(target.bucket),"objectName "+meta(target.path),"contentType "+meta(file.type||"audio/mpeg"),"cacheControl "+meta("3600")].join(",")};
 const create=await fetch(endpoint,{method:"POST",headers});if(!create.ok)throw new Error("Could not start resumable upload");let loc=create.headers.get("location");if(!loc)throw new Error("Upload location missing");if(loc.startsWith("/"))loc=new URL(loc,endpoint).toString();
 let off=0;while(off<file.size){const chunk=file.slice(off,Math.min(file.size,off+offsetStep));const r=await fetch(loc,{method:"PATCH",headers:{authorization:"Bearer "+token,apikey:PUB,"Tus-Resumable":"1.0.0","Upload-Offset":String(off),"Content-Type":"application/offset+octet-stream"},body:chunk});if(!r.ok)throw new Error("Upload failed at "+Math.round(off/file.size*100)+"%");off=Number(r.headers.get("upload-offset")||off+chunk.size);$("#audioProgress").style.width=Math.round(off/file.size*100)+"%"}
}
$("#uploadAudio").onclick=async()=>{const file=$("#audioFile").files[0],track=$("#audioTrack").value;if(!file||!track)return msg($("#uploadMsg"),"Choose a track and audio file.",true);try{$("#audioProgress").style.width="0";msg($("#uploadMsg"),"Preparing upload…");const target=await api("upload_target",{kind:"audio",filename:file.name});await tusUpload(file,target);await api("attach_audio",{track_id:track,path:target.path});msg($("#uploadMsg"),"Master uploaded securely.");await load()}catch(e){msg($("#uploadMsg"),e.message,true)}};
if(token)load();
</script></body></html>`;
Deno.serve(()=>new Response(html,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"public,max-age=60","x-content-type-options":"nosniff","x-frame-options":"DENY","referrer-policy":"strict-origin-when-cross-origin"}}));