import { supabase } from '../lib/supabaseClient'
function ensureSupabase(){if(!supabase)throw new Error('Supabase is not configured.')}
export async function toggleFollow(userId,artistId){ensureSupabase();const{data:existing,error:lookupError}=await supabase.from('artist_follows').select('id').eq('user_id',userId).eq('artist_id',artistId).maybeSingle();if(lookupError)throw lookupError;if(existing){const{error}=await supabase.from('artist_follows').delete().eq('id',existing.id);if(error)throw error;return false}const{error}=await supabase.from('artist_follows').insert({user_id:userId,artist_id:artistId});if(error)throw error;return true}
export async function toggleLike(userId,trackId){ensureSupabase();const{data:existing,error:lookupError}=await supabase.from('track_likes').select('id').eq('user_id',userId).eq('track_id',trackId).maybeSingle();if(lookupError)throw lookupError;if(existing){const{error}=await supabase.from('track_likes').delete().eq('id',existing.id);if(error)throw error;return false}const{error}=await supabase.from('track_likes').insert({user_id:userId,track_id:trackId});if(error)throw error;return true}
export async function getFanProfile(userId){ensureSupabase();const{data,error}=await supabase.from('fan_profiles').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;return data}
export async function saveFanProfile(userId,values){ensureSupabase();const payload={user_id:userId,username:values.username?.trim().toLowerCase()||null,display_name:values.display_name?.trim()||null,bio:values.bio?.trim()||null,is_public:Boolean(values.is_public),updated_at:new Date().toISOString()};const{data,error}=await supabase.from('fan_profiles').upsert(payload).select().single();if(error)throw error;return data}
export async function getPlaylists(userId){ensureSupabase();const{data,error}=await supabase.from('playlists').select('*, playlist_items(count)').eq('user_id',userId).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function createPlaylist(userId,name,isPublic=false){ensureSupabase();const slugBase=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'playlist';const slug=`${slugBase}-${crypto.randomUUID().slice(0,8)}`;const{data,error}=await supabase.from('playlists').insert({user_id:userId,name:name.trim(),slug,is_public:isPublic}).select().single();if(error)throw error;return data}
export async function updatePlaylist(playlistId,changes){ensureSupabase();const{data,error}=await supabase.from('playlists').update(changes).eq('id',playlistId).select().single();if(error)throw error;return data}
export async function deletePlaylist(playlistId){ensureSupabase();const{error}=await supabase.from('playlists').delete().eq('id',playlistId);if(error)throw error}
export async function getPublicPlaylist(slug){ensureSupabase();const{data,error}=await supabase.from('playlists').select('id,name,slug,is_public,created_at,playlist_items(id,position,track_id,tracks(id,title,release_id,releases(title,primary_artist,status)))').eq('slug',slug).eq('is_public',true).maybeSingle();if(error)throw error;return data}
export async function getListeningHistory(userId){ensureSupabase();const{data,error}=await supabase.from('listening_history').select('id,played_at,track_id,tracks(id,title,releases(title,primary_artist,slug))').eq('user_id',userId).order('played_at',{ascending:false}).limit(25);if(error)throw error;return data||[]}
