import { useMemo, useState } from 'react'

const prompts={
  metadata:'Improve this release metadata for clarity and discoverability without inventing credits, rights or achievements.',
  marketing:'Create a practical 14-day release campaign using only facts supplied by the creator.',
  planning:'Review the release readiness information and identify missing operational steps before submission.',
}

export default function AICreatorSuite(){const[type,setType]=useState('metadata');const[input,setInput]=useState('');const[result,setResult]=useState('');const template=useMemo(()=>prompts[type],[type]);function prepare(e){e.preventDefault();if(!input.trim())return;setResult(`${template}\n\nCreator context:\n${input.trim()}\n\nProvider status: not connected. This request is prepared but has not been sent to an external AI service.`)}return <main className="container page-pad"><p className="eyebrow">AI CREATOR SUITE</p><h1>Assistance with guardrails.</h1><p className="lede">The V1 interface prepares consent-aware creator requests. External AI execution remains disabled until an approved provider is connected server-side with usage controls and audit logging.</p><section className="panel"><form className="stack" onSubmit={prepare}><label>Assistant mode<select value={type} onChange={e=>setType(e.target.value)}><option value="metadata">Metadata coach</option><option value="marketing">Marketing planner</option><option value="planning">Release readiness</option></select></label><label>Creator context<textarea rows="8" value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste only information you want the assistant to use."/></label><button className="pill-button">Prepare request</button></form></section>{result&&<section className="panel" style={{marginTop:20}}><p className="eyebrow">PREPARED REQUEST</p><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',lineHeight:1.65}}>{result}</pre></section>}<div className="notice">No training consent is implied. No request leaves the browser in this build.</div></main>}
