-- ALLEGRO creator-growth and moderation production schema snapshot
-- Applied to Supabase project yfawrenhudjomhnglfhq on 2026-09-25.
-- This file documents the live schema changes; it is intentionally stored
-- outside supabase/migrations because the changes were applied directly
-- during production iteration and should be converted into a formal migration
-- with the Supabase CLI before a future clean-room rebuild.

create table if not exists public.allegro_funnel_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  user_id uuid references auth.users(id) on delete set null,
  artist_id uuid references public.allegro_artists(id) on delete set null,
  track_id uuid references public.allegro_tracks(id) on delete set null,
  source text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.allegro_funnel_events enable row level security;
revoke all on public.allegro_funnel_events from anon, authenticated;

drop policy if exists "allegro_funnel_explicit_deny" on public.allegro_funnel_events;
create policy "allegro_funnel_explicit_deny"
on public.allegro_funnel_events
for all to anon,authenticated
using (false)
with check (false);

create unique index if not exists allegro_funnel_authenticated_user_once
  on public.allegro_funnel_events(event_name,user_id)
  where event_name='creator_authenticated' and user_id is not null;

create index if not exists allegro_funnel_events_created_idx
  on public.allegro_funnel_events(created_at desc);
create index if not exists allegro_funnel_events_name_idx
  on public.allegro_funnel_events(event_name,created_at desc);
create index if not exists allegro_funnel_events_user_idx
  on public.allegro_funnel_events(user_id) where user_id is not null;
create index if not exists allegro_funnel_events_artist_idx
  on public.allegro_funnel_events(artist_id) where artist_id is not null;
create index if not exists allegro_funnel_events_track_idx
  on public.allegro_funnel_events(track_id) where track_id is not null;

alter table public.allegro_moderation_queue
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null;

create index if not exists allegro_moderation_queue_reviewed_by_idx
  on public.allegro_moderation_queue(reviewed_by) where reviewed_by is not null;
create index if not exists allegro_moderation_queue_submitted_by_idx
  on public.allegro_moderation_queue(submitted_by) where submitted_by is not null;

create table if not exists public.allegro_moderation_audit (
  id bigint generated by default as identity primary key,
  moderation_id uuid not null references public.allegro_moderation_queue(id) on delete cascade,
  entity_type text not null,
  entity_id uuid not null,
  reviewer_id uuid references auth.users(id) on delete set null,
  decision text not null check (decision in ('approved','changes_requested','rejected')),
  notes text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.allegro_moderation_audit enable row level security;
revoke all on public.allegro_moderation_audit from anon, authenticated;

drop policy if exists "allegro_moderation_audit_explicit_deny" on public.allegro_moderation_audit;
create policy "allegro_moderation_audit_explicit_deny"
on public.allegro_moderation_audit
for all to anon,authenticated
using (false)
with check (false);

create index if not exists allegro_moderation_audit_entity_idx
  on public.allegro_moderation_audit(entity_type,entity_id,created_at desc);
create index if not exists allegro_moderation_audit_moderation_idx
  on public.allegro_moderation_audit(moderation_id);
create index if not exists allegro_moderation_audit_reviewer_idx
  on public.allegro_moderation_audit(reviewer_id) where reviewer_id is not null;
