-- ALLEGRO RADIO 24/7 programming, rights clearance, advertising and playout evidence.

create table if not exists public.radio_programs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  day text not null default 'daily' check (day in ('daily','sun','mon','tue','wed','thu','fri','sat')),
  start_time time not null,
  end_time time not null,
  genre text,
  description text,
  priority integer not null default 0,
  explicit_allowed boolean not null default true,
  live_takeover_allowed boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.radio_tracks (
  id uuid primary key default gen_random_uuid(),
  release_id uuid references public.releases(id) on delete set null,
  artist_id uuid,
  artist_name text not null,
  title text not null,
  audio_path text not null,
  duration_seconds integer not null check (duration_seconds between 30 and 7200),
  genres text[] not null default '{}',
  territories text[] not null default array['ZA']::text[],
  explicit boolean not null default false,
  rights_status text not null default 'pending' check (rights_status in ('pending','verified','blocked')),
  radio_clearance text not null default 'pending' check (radio_clearance in ('pending','cleared','blocked')),
  clearance_reference text,
  clearance_expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.radio_ad_campaigns (
  id uuid primary key default gen_random_uuid(),
  advertiser_name text not null,
  campaign_name text not null,
  creative_audio_path text not null,
  duration_seconds integer not null check (duration_seconds between 5 and 180),
  starts_at timestamptz,
  ends_at timestamptz,
  max_daily_plays integer not null default 24 check (max_daily_plays between 1 and 10000),
  priority integer not null default 0,
  approved boolean not null default false,
  status text not null default 'draft' check (status in ('draft','active','paused','ended')),
  created_at timestamptz not null default now()
);

create table if not exists public.radio_live_sessions (
  id uuid primary key default gen_random_uuid(),
  presenter_user_id uuid references auth.users(id) on delete set null,
  presenter_name text not null,
  program_id uuid references public.radio_programs(id) on delete set null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'scheduled' check (status in ('scheduled','live','ended','cancelled')),
  ingest_key_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.radio_playout_log (
  id bigint generated by default as identity primary key,
  program_id uuid references public.radio_programs(id) on delete set null,
  track_id uuid references public.radio_tracks(id) on delete set null,
  ad_campaign_id uuid references public.radio_ad_campaigns(id) on delete set null,
  live_session_id uuid references public.radio_live_sessions(id) on delete set null,
  item_type text not null check (item_type in ('track','ad','jingle','talk','live')),
  title text not null,
  artist_name text,
  started_at timestamptz not null,
  ended_at timestamptz,
  duration_seconds integer,
  proof_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists radio_tracks_clearance_idx on public.radio_tracks (radio_clearance, rights_status, active);
create index if not exists radio_programs_active_idx on public.radio_programs (active, day, start_time);
create index if not exists radio_ads_active_idx on public.radio_ad_campaigns (status, approved, starts_at, ends_at);
create index if not exists radio_playout_started_idx on public.radio_playout_log (started_at desc);

alter table public.radio_programs enable row level security;
alter table public.radio_tracks enable row level security;
alter table public.radio_ad_campaigns enable row level security;
alter table public.radio_live_sessions enable row level security;
alter table public.radio_playout_log enable row level security;

drop policy if exists "radio programs public read" on public.radio_programs;
create policy "radio programs public read" on public.radio_programs for select using (active = true);

drop policy if exists "radio cleared track metadata public read" on public.radio_tracks;
create policy "radio cleared track metadata public read" on public.radio_tracks for select using (active = true and rights_status = 'verified' and radio_clearance = 'cleared');

drop policy if exists "radio active ads public read" on public.radio_ad_campaigns;
create policy "radio active ads public read" on public.radio_ad_campaigns for select using (status = 'active' and approved = true);

drop policy if exists "radio recent playout public read" on public.radio_playout_log;
create policy "radio recent playout public read" on public.radio_playout_log for select using (started_at > now() - interval '24 hours');

create or replace view public.radio_now_playing as
select
  l.id,
  l.started_at,
  l.ended_at,
  l.title as track_title,
  l.artist_name,
  l.item_type,
  p.name as program_name
from public.radio_playout_log l
left join public.radio_programs p on p.id = l.program_id
where l.started_at <= now()
  and (l.ended_at is null or l.ended_at > now())
order by l.started_at desc
limit 1;

grant select on public.radio_now_playing to anon, authenticated;

insert into public.radio_programs(name,day,start_time,end_time,genre,description,priority)
select * from (values
  ('Sunrise Africa','daily','05:00'::time,'09:00'::time,'afropop','Energy, headlines, culture and new African music.',10),
  ('Vibez All Day','daily','09:00'::time,'15:00'::time,'afropop','Music-first daytime programming with creator stories.',10),
  ('Africa Drive','daily','15:00'::time,'19:00'::time,'amapiano','Drive-time music, entertainment, interviews and audience interaction.',20),
  ('Night Pulse','daily','19:00'::time,'00:00'::time,'rnb','R&B, soul, hip-hop and live guest sessions.',10),
  ('After Dark','daily','00:00'::time,'05:00'::time,'mixed','Autopilot discovery, classics and emerging talent.',5)
) as seed(name,day,start_time,end_time,genre,description,priority)
where not exists (select 1 from public.radio_programs);
